# Generated by Django 2.0.4 on 2018-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.DateField(verbose_name='日期')),
                ('uv', models.IntegerField()),
                ('pv', models.IntegerField()),
                ('game_uv', models.IntegerField()),
                ('game_pv', models.IntegerField()),
                ('count_new_user', models.IntegerField()),
                ('total_user', models.IntegerField()),
                ('total_pay_user', models.IntegerField()),
                ('p_uv', models.IntegerField()),
                ('p_pv', models.IntegerField()),
                ('p_s_uv', models.IntegerField()),
                ('p_s_pv', models.IntegerField()),
                ('p_e_uv', models.IntegerField()),
                ('p_e_pv', models.IntegerField()),
                ('c_percent', models.IntegerField()),
                ('already_pay_user', models.IntegerField()),
                ('p_new_count', models.IntegerField()),
                ('never_pay_user', models.IntegerField()),
                ('p_s_money', models.IntegerField()),
                ('p_e_money', models.IntegerField()),
                ('hall_type', models.CharField(max_length=128)),
                ('serverId', models.IntegerField()),
                ('area_code', models.IntegerField()),
                ('remark', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': '每日数据统计',
                'db_table': 'rh_month_reports',
            },
        ),
    ]
