# Generated by Django 2.0.4 on 2018-08-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20180802_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='group',
            field=models.CharField(max_length=128, null=True, verbose_name='二级菜单下的菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[(0, '有效'), (1, '无效')], default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
