# Generated by Django 2.0.4 on 2018-08-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180802_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanOrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_userid', models.CharField(max_length=128)),
                ('order_url', models.CharField(default='', max_length=1280)),
                ('add_time', models.DateTimeField(null=True)),
                ('is_order', models.CharField(default='F', max_length=2)),
                ('order_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': '可订购信息',
                'db_table': 'rh_can_order_info',
            },
        ),
        migrations.AlterField(
            model_name='dayreports',
            name='c_percent',
            field=models.IntegerField(verbose_name='转化率'),
        ),
        migrations.AlterField(
            model_name='dayreports',
            name='p_s_uv',
            field=models.IntegerField(verbose_name='成功订购用户数'),
        ),
        migrations.AlterField(
            model_name='dayreports',
            name='pv',
            field=models.IntegerField(verbose_name='PV'),
        ),
        migrations.AlterField(
            model_name='dayreports',
            name='uv',
            field=models.IntegerField(verbose_name='UV'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='group',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='二级菜单下的菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.IntegerField(choices=[(1, '有效'), (0, '无效')], default=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
