# Generated by Django 2.0.4 on 2018-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180808_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='canorderinfo',
            name='product_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
