# Generated by Django 2.0.4 on 2018-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_canorderinfo_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='canorderinfo',
            name='remark',
            field=models.CharField(max_length=128, null=True, verbose_name='返回信息'),
        ),
    ]
