# Generated by Django 2.0.4 on 2018-07-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_key', models.CharField(default='', help_text='活动编码', max_length=128, verbose_name='活动编码')),
                ('c_name', models.CharField(default='', help_text='活动名称', max_length=128, verbose_name='活动名称')),
                ('c_url', models.CharField(blank=True, default='', help_text='活动入口地址', max_length=255, verbose_name='活动地址')),
                ('c_image_url', models.CharField(blank=True, default='', help_text='活动图片地址', max_length=255, verbose_name='活动图片')),
                ('c_image_url_sed', models.CharField(blank=True, default='', help_text='(选中)活动图片地址', max_length=255, verbose_name='(选中)活动图片')),
                ('c_priority', models.IntegerField(default=0, help_text='显示的优先级', verbose_name='优先级')),
                ('c_is_open', models.SmallIntegerField(choices=[(1, '开放'), (0, '不开放')], default=1, help_text='是否显示在活动列表中', verbose_name='是否开放')),
                ('c_time', models.DateTimeField(auto_now_add=True, help_text='记录产生时间', null=True, verbose_name='时间')),
                ('c_starttime', models.DateTimeField(help_text='开始时间', null=True, verbose_name='活动开始时间')),
                ('c_endtime', models.DateTimeField(help_text='结束时间', null=True, verbose_name='活动结束时间')),
                ('enable', models.CharField(choices=[('T', '有效'), ('F', '无效')], default='T', max_length=2, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '首页表',
                'db_table': 'hall_home',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_key', models.CharField(default='', help_text='位置键值(英文)', max_length=128, verbose_name='位置键值')),
                ('c_name', models.CharField(default='', help_text='位置名称(中文)', max_length=128, verbose_name='位置名称')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='记录产生时间', null=True, verbose_name='创建时间')),
                ('location_type', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='位置类型')),
                ('enable', models.CharField(choices=[('T', '有效'), ('F', '无效')], default='T', max_length=2, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '位置',
                'db_table': 'hall_location',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='location',
            field=models.ForeignKey(on_delete=False, to='hall.Location'),
        ),
    ]
